# Generated by Django 2.0.2 on 2018-03-15 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('id_off', models.BigIntegerField()),
                ('brands', models.CharField(max_length=200)),
                ('nutrition_grade', models.CharField(max_length=1)),
                ('satured_fat', models.FloatField()),
                ('fat', models.FloatField()),
                ('sugar', models.FloatField()),
                ('salt', models.FloatField()),
                ('categorie', models.CharField(max_length=100)),
                ('img_url', models.URLField()),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'produit',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorited', to='home.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
            },
        ),
    ]
