# Generated by Django 2.0.2 on 2018-02-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('id_off', models.IntegerField()),
                ('brands', models.CharField(max_length=200)),
                ('nutrition_grade', models.CharField(max_length=1)),
                ('satured_fat', models.FloatField()),
                ('fat', models.FloatField()),
                ('sugar', models.FloatField()),
                ('salt', models.FloatField()),
                ('categorie', models.CharField(max_length=100)),
                ('img_url', models.URLField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=100)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorited', to='home.Product')),
            ],
        ),
    ]
