# Generated by Django 2.0.2 on 2018-03-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('id_off', models.IntegerField()),
                ('brands', models.CharField(max_length=200)),
                ('nutrition_grade', models.CharField(max_length=1)),
                ('satured_fat', models.FloatField()),
                ('fat', models.FloatField()),
                ('sugar', models.FloatField()),
                ('salt', models.FloatField()),
                ('categorie', models.CharField(max_length=100)),
                ('img_url', models.URLField()),
                ('url', models.URLField()),
            ],
        ),
    ]
